# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-30 00:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidadao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, null=True)),
                ('apelido', models.CharField(max_length=20, null=True)),
                ('num_bi', models.PositiveIntegerField(null=True)),
                ('morada', models.CharField(max_length=100, null=True)),
                ('codigo_postal', models.CharField(max_length=8, null=True)),
                ('telefone', models.PositiveIntegerField(null=True)),
                ('nro_eleitor', models.PositiveIntegerField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=3000)),
                ('data_insercao', models.DateTimeField(auto_now_add=True)),
                ('data_evento', models.DateField()),
                ('imagem', models.BinaryField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ficheiro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=3000)),
                ('data_insercao', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('ACAO', 'Plano de Acao'), ('CONTAS', 'Relatorio de Contas'), ('ACTAS', 'Actas de Reuniao'), ('OUTRO', 'Outros')], default='OUTRO', max_length=20)),
                ('ficheiro', models.FileField(upload_to='documents/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=3000)),
                ('data_insercao', models.DateTimeField(auto_now_add=True)),
                ('imagem', models.BinaryField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
