# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-12 18:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20170412_1848'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='noticia',
            table='noticia',
        ),
    ]
