# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-03 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_questionario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionario',
            name='quest',
            field=models.CharField(max_length=400),
        ),
    ]
