# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-09 11:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0005_auto_20170509_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opcao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Votacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='pergunta',
            name='respostas',
        ),
        migrations.RemoveField(
            model_name='pergunta',
            name='utilizadores',
        ),
        migrations.AddField(
            model_name='pergunta',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='Resposta',
        ),
        migrations.AddField(
            model_name='votacao',
            name='pergunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Pergunta'),
        ),
        migrations.AddField(
            model_name='votacao',
            name='respondido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Opcao'),
        ),
        migrations.AddField(
            model_name='votacao',
            name='utilizador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='opcao',
            name='pergunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Pergunta'),
        ),
    ]
