# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-17 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp', '0006_auto_20170412_1958'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidadao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permissao', models.CharField(max_length=1)),
                ('username', models.CharField(max_length=20)),
                ('nome', models.CharField(max_length=20)),
                ('apelido', models.CharField(max_length=20)),
                ('num_bi', models.PositiveIntegerField()),
                ('morada', models.CharField(max_length=100)),
                ('codigo_postal', models.CharField(max_length=8)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.PositiveIntegerField()),
                ('nro_eleitor', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=3000)),
                ('data_insercao', models.DateTimeField()),
                ('imagem', models.BinaryField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
