# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-18 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_cidadao_noticia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=3000)),
                ('data_insercao', models.DateTimeField(auto_now_add=True)),
                ('data_evento', models.DateField()),
                ('imagem', models.BinaryField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='noticia',
            name='data_insercao',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
