# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-28 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20170418_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ficheiro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=3000)),
                ('data_insercao', models.DateTimeField(auto_now_add=True)),
                ('ficheiro', models.FileField(upload_to='documents/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
