# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-28 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_ficheiro'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficheiro',
            name='tipo',
            field=models.CharField(choices=[('ACAO', 'Plano de Acao'), ('CONTAS', 'Relatorio de Contas'), ('ACTAS', 'Actas de Reuniao'), ('OUTRO', 'Outros')], default='OUTRO', max_length=20),
        ),
        migrations.AlterField(
            model_name='ficheiro',
            name='ficheiro',
            field=models.FileField(upload_to='myapp/static/documents/'),
        ),
    ]
